name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit
    permissions:
      security-events: write
      contents: read
